FROM python:3.8-slim-buster

LABEL environment="Sample Docker Image for class 24"

WORKDIR /app

COPY . .

ENV DATABASE_PASSWORD="mysamplepassword"

EXPOSE 8083

RUN pip install -r requirements.txt

CMD ["python3","app.py"]