version: "3.9"

services:
  db:
    image: postgres:16
    container_name: lab_db
    environment:
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass
      POSTGRES_DB: labdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U labuser -d labdb"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: ./web
    container_name: lab_web
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=labdb
      - DB_USER=labuser
      - DB_PASSWORD=labpass
      - FLASK_ENV=production
    ports:
      - "8085:5000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
